version: '3.1'

services:
     nginx:
        image: nginx:1.13.7
        container_name: nginx
        depends_on:
           - flask
        volumes:
           - ./nginx.conf:/etc/nginx/conf.d/default.conf
           - ./certs/localhost.crt:/etc/nginx/conf.d/localhost.crt
           - ./certs/localhost.key:/etc/nginx/conf.d/localhost.key
        networks:
           - rakuten
        ports:
           - 80:80
           - 443:443

     flask:
        build:
           context:  ./
           dockerfile: Dockerfile
        image: flask:0.0.1
        container_name: flask
        volumes:
           - ./:/code
        environment:
           - FLASK_APP=/code/app.py
        command: flask run --host=0.0.0.0
        networks:
           rakuten:
              aliases:
               - flask-app

        ports:
           - 8080:5000


networks:
    rakuten:
